---
# docker-compose for Laravel 11, PHP 8.2, NGINX, Postgresql 17

services:
  nginx:
    # change this to the public hostname for your site
    hostname: "cms1.lan.dkxl.biz"
    image: "nginx:stable-alpine-slim"
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - laravel
    networks:
      - laravel
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/keys:/etc/nginx/keys
      - ./nginx/club-manager.conf:/etc/nginx/conf.d/default.conf
      - ../:/srv/app

  laravel:
    container_name: laravel
    build:
      context: "./laravel"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - laravel
    volumes:
      - ./laravel/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ../:/srv/app
    post_start:
      - command: chown -R www-data:www-data /srv/app/storage
    environment:
      TZ: "Etc/UTC"
      DB_HOST: db
      DB_NAME: appt
      DB_USER: appt_admin
      DB_PASSWORD: change_me
      # change this to the public hostname for your site
      APP_URL: "https://cms1.lan.dkxl.biz"

  db:
    image: "postgres:17-bookworm"
    container_name: db
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    networks:
      - laravel
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: appt
      POSTGRES_USER: appt_admin
      POSTGRES_PASSWORD: change_me

#  Useful for development - not essential for production sites
  db_admin:
    image: adminer
    container_name: db_admin
    restart: unless-stopped
    networks:
      - laravel
    depends_on:
      - db
    ports:
      - "8080:8080"

networks:
  laravel:

volumes:
  db-data:
